language: php
env:
  global:
    - XDEBUG_MODE=coverage

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot
  - nightly

dist: xenial
sudo: false

matrix:
  allow_failures:
    - php: 7.4snapshot
    - php: nightly

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - vendor/bin/phpcs --standard=psr2 src/
  - vendor/bin/phpunit
