<?php


namespace NFePHP\MDFe\Tests;

use NFePHP\MDFe\Make;
use NFePHP\MDFe\Tests\Helpers\FakeToolsTrait;
use NFePHP\MDFe\Tests\Helpers\MakeBuilder;
use PHPUnit\Framework\TestCase;


class MakeTest extends TestCase
{
    use FakeToolsTrait;

    /**
     * @var \NFePHP\MDFe\Tests\Helpers\MakeBuilder
     */
    private $makeBuilder;

    public function setUp()
    {
        $this->makeBuilder = new MakeBuilder();
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function test_valid_xml()
    {
        $make = $this->makeBuilder->buildWithVAdiant();
        $xml = $make->getXML();
        $this->assertNotEmpty($xml);
        $tools = $this->getFakeTools();
        $signedXml = $tools->signMDFe($xml);
        $tools->sefazEnviaLote([$signedXml], 1);
        $params = $tools->getSendParams();
        $this->assertEquals('mdfeRecepcaoLote', $params->getOperation());
    }

    public function test_tag_inf_pag_v_adiant()
    {
        $make = $this->makeBuilder->buildWithVAdiant();
        $xml = $make->getXML();
        $this->assertStringContainsString("<vAdiant>0.50</vAdiant>", $xml);
    }
    
}
